// src/pages/api/lead.ts
// Handles primary lead/inquiry form submissions (name, email, company, goal, etc.).
// DO NOT edit this file per client — update src/lib/email.config.ts instead.

import type { APIRoute } from 'astro';
import { Resend } from 'resend';
import mailchimp from '@mailchimp/mailchimp_marketing';
import { EMAIL_CONFIG } from '~/lib/email.config';

const resend = new Resend(import.meta.env.RESEND_API_KEY);

if (EMAIL_CONFIG.mailchimp.enabled) {
  mailchimp.setConfig({
    apiKey: import.meta.env.MAILCHIMP_API_KEY,
    server: import.meta.env.MAILCHIMP_SERVER_PREFIX,
  });
}

export const POST: APIRoute = async ({ request }) => {
  try {
    const data    = await request.formData();
    const get = (k: string) => data.get(k)?.toString().trim() ?? '';
    const firstName = get('firstName');
    const lastName  = get('lastName');
    const name    = get('name') || [firstName, lastName].filter(Boolean).join(' ');
    const email   = get('email');
    const company = get('company');
    const phone   = get('phone');
    const goal    = get('goal');
    const source  = get('source');
    // Extra fields the richer lead forms send (optional)
    const hq         = get('hq');
    const portfolio  = get('portfolio');
    const states     = get('states');
    const referredBy = get('referred_by');

    // Any other named fields the form sends (property type, units, timeline, role,
    // relationship, etc.) — rendered generically so no submission is silently dropped.
    const KNOWN = new Set([
      'firstName', 'lastName', 'name', 'email', 'company', 'phone',
      'goal', 'source', 'hq', 'portfolio', 'states', 'referred_by',
    ]);
    const extras = [...data.entries()]
      .filter(([k, v]) => !KNOWN.has(k) && typeof v === 'string' && v.trim())
      .map(([k, v]) => [
        k.replace(/[_-]+/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
        (v as string).trim(),
      ]);

    if (!email || !name) {
      return new Response(JSON.stringify({ error: 'Name and email are required.' }), { status: 400 });
    }

    // Internal notification
    try {
      await resend.emails.send({
        from: EMAIL_CONFIG.from.notifications,
        to: EMAIL_CONFIG.notify,
        cc: EMAIL_CONFIG.notifyCc,
        replyTo: EMAIL_CONFIG.replyTo,
        subject: `New lead: ${company || name}`,
        html: `
          <h2>New Lead Form Submission</h2>
          <p><strong>Name:</strong> ${name}</p>
          <p><strong>Email:</strong> ${email}</p>
          ${company ? `<p><strong>Company:</strong> ${company}</p>` : ''}
          ${hq         ? `<p><strong>Headquartered:</strong> ${hq}</p>` : ''}
          ${portfolio  ? `<p><strong>Portfolio size:</strong> ${portfolio}</p>` : ''}
          ${states     ? `<p><strong>States:</strong> ${states}</p>` : ''}
          ${phone   ? `<p><strong>Phone:</strong> ${phone}</p>` : ''}
          ${referredBy ? `<p><strong>Referred by:</strong> ${referredBy}</p>` : ''}
          ${goal    ? `<p><strong>What's prompting the conversation:</strong> ${goal}</p>` : ''}
          ${extras.map(([k, v]) => `<p><strong>${k}:</strong> ${v}</p>`).join('')}
          ${source  ? `<hr><p style="color:#888;font-size:13px"><strong>Source</strong><br>${source.replace(/\n/g, '<br>')}</p>` : ''}
        `,
      });
    } catch (err) {
      console.error('Resend notify error:', err);
    }

    // Confirmation to sender
    try {
      // Board inquiries (Find a Management Company) get service-oriented copy;
      // CAM-owner leads get the peer/independence voice.
      const isBoard = /board|management company/i.test(source);
      const leadCopy = isBoard ? EMAIL_CONFIG.copy.board : EMAIL_CONFIG.copy.lead;
      await resend.emails.send({
        from: EMAIL_CONFIG.from.hello,
        to: email,
        replyTo: EMAIL_CONFIG.replyTo,
        subject: leadCopy.confirmSubject,
        html: leadCopy.confirmBody(name, company, EMAIL_CONFIG.brand.url),
      });
    } catch (err) {
      console.error('Resend confirm error:', err);
    }

    // Always add leads to Mailchimp
    if (EMAIL_CONFIG.mailchimp.enabled) {
      try {
        await mailchimp.lists.addListMember(import.meta.env.MAILCHIMP_AUDIENCE_ID, {
          email_address: email,
          status: 'subscribed',
          merge_fields: {
            FNAME:   name.split(' ')[0],
            LNAME:   name.split(' ').slice(1).join(' '),
            COMPANY: company,
          },
          tags: [...EMAIL_CONFIG.mailchimp.defaultTags, 'lead-form'],
        });
      } catch (err: any) {
        console.error('Mailchimp lead error:', err?.response?.body ?? err);
      }
    }

    return new Response(JSON.stringify({ success: true }), { status: 200 });
  } catch (err) {
    console.error('Lead API error:', err);
    return new Response(JSON.stringify({ error: 'Something went wrong. Please try again.' }), { status: 500 });
  }
};
