// src/pages/api/subscribe.ts
// Handles newsletter/email list opt-ins (email only, name optional).
// DO NOT edit this file per client — update src/lib/email.config.ts instead.

import type { APIRoute } from 'astro';
import mailchimp from '@mailchimp/mailchimp_marketing';
import { Resend } from 'resend';
import { EMAIL_CONFIG } from '~/lib/email.config';
import { checkSpam } from '~/lib/spam';

const resend = new Resend(import.meta.env.RESEND_API_KEY);

if (EMAIL_CONFIG.mailchimp.enabled) {
  mailchimp.setConfig({
    apiKey: import.meta.env.MAILCHIMP_API_KEY,
    server: import.meta.env.MAILCHIMP_SERVER_PREFIX,
  });
}

export const POST: APIRoute = async ({ request }) => {
  try {
    const data      = await request.formData();
    const email     = data.get('email')?.toString().trim()     ?? '';
    const firstName = data.get('firstName')?.toString().trim() ?? '';

    if (!email) {
      return new Response(JSON.stringify({ error: 'Email is required.' }), { status: 400 });
    }

    // Anti-spam — report success, subscribe nothing (see src/lib/spam.ts).
    const startedAt = Number(data.get('form_started')?.toString() ?? '');
    const verdict = checkSpam({
      honeypot: data.get('company_url')?.toString(),
      elapsedMs: startedAt ? Date.now() - startedAt : undefined,
      email,
      text: [firstName],
    });
    if (verdict.spam) {
      console.warn('Subscribe blocked as spam:', verdict.reason, '|', email);
      return new Response(JSON.stringify({ success: true }), { status: 200 });
    }

    // Add to Mailchimp (silently pass if already subscribed)
    if (EMAIL_CONFIG.mailchimp.enabled) {
      try {
        await mailchimp.lists.addListMember(import.meta.env.MAILCHIMP_AUDIENCE_ID, {
          email_address: email,
          status: 'subscribed',
          merge_fields: { FNAME: firstName },
          tags: EMAIL_CONFIG.mailchimp.defaultTags,
        });
      } catch (err: any) {
        const alreadyExists = err?.response?.body?.title === 'Member Exists';
        if (!alreadyExists) {
          console.error('Mailchimp subscribe error:', err?.response?.body ?? err);
          return new Response(JSON.stringify({ error: 'Could not subscribe. Please try again.' }), { status: 500 });
        }
      }
    }

    // Welcome email
    try {
      await resend.emails.send({
        from: EMAIL_CONFIG.from.hello,
        to: email,
        replyTo: EMAIL_CONFIG.replyTo,
        subject: EMAIL_CONFIG.copy.subscribe.confirmSubject,
        html: EMAIL_CONFIG.copy.subscribe.confirmBody(firstName),
      });
    } catch (err) {
      console.error('Resend welcome error:', err);
    }

    return new Response(JSON.stringify({ success: true }), { status: 200 });
  } catch (err) {
    console.error('Subscribe API error:', err);
    return new Response(JSON.stringify({ error: 'Something went wrong. Please try again.' }), { status: 500 });
  }
};
